# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            trydis' blog
description:      'Ramblings about .NET and mobile stuff'
url:              http://trydis.github.io
baseurl:          /

paginate:         5

# Twitter
twitter_handle: trydis
twitter_widget_id: 550443660773691394