# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            trydis
description:      'Ramblings on coding related topics'
url:              https://trydis.github.io
baseurl:          /

paginate:         5

# Twitter
twitter_handle: trydis
twitter_widget_id: 550443660773691394